version: "3.9"

services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: echo_postgres
    restart: always
    environment:
      POSTGRES_USER: echo_user
      POSTGRES_PASSWORD: echo_password
      POSTGRES_DB: echo_db
    ports:
      - "5433:5432"
    volumes:
      - echo_pgdata:/var/lib/postgresql/data:Z

volumes:
  echo_pgdata:
